" comments in vimscript start with a `"`.
"test text"

" if you open this file in vim, it'll be syntax highlighted for you.

"legacy some vi compatability"
set nocompatible

set noshowmatch

" Turn on syntax highlighting.
syntax on
set synmaxcol=2000

" Disable the default Vim startup message.
set shortmess+=I

" Show line numbers.
set number

" Makes pasting normal.
"set paste

" Always show the status line at the bottom, even if you only have one window open.
set laststatus=2

"Normal back space behaviour"
set backspace=indent,eol,start

"Auto reloadd"
set autoread

"Allow existance of hidden usaved tabs more info `:help hidden`"
set hidden

"Ignore case search always Smart search with capitals"
set ignorecase
set smartcase

" Enable searching as you type, rather than waiting till you press enter.
set incsearch
set hlsearch

" Local configs
set exrc

" Unbind some useless/annoying default key bindings.
nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

" Disable audible bell because it's annoying.
set noerrorbells visualbell t_vb=

" Enable mouse support. You should avoid relying on this too much, but it can
" sometimes be convenient.
set mouse+=a


"Copy to clip-board"
noremap <C-y> "+y

"Remap esc to jk/kj"
imap jk <Esc>
imap kj <Esc>

"viminfo file location"
set viminfo+=n~/.vim/viminfo

"Tabs for python
set tabstop=4 
set shiftwidth=4
" set smarttab
set expandtab "Replace tab with spaces
set softtabstop=4 "4 spaces in tab

"Tab switch shortcuts
nnoremap gr :tabprevious<CR>

set autoindent 

"syntax highlit for python"
"let python_highlight_all = 1

"Turn on all colors
set t_Co=256

"To display longer lines"
set wrap
set linebreak

"Turn off backups of files"
set nobackup
set noswapfile

"Ruler"
set ruler

"Plugins"
call plug#begin('~/.vim/plugged')
    Plug 'maxboisvert/vim-simple-complete'
    Plug 'tpope/vim-vinegar'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
    Plug 'mbbill/undotree'
call plug#end()

"Undo tree
nnoremap <F5> :UndotreeToggle<CR>

"Nerd tree shortcuts"
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <leader>f :NERDTreeFind<CR>
nnoremap <C-t> :NERDTreeToggle<CR>

"Easy motion bindings"
map <Space>f <Plug>(easymotion-f)
map <Space>F <Plug>(easymotion-F)

"Tag file serach"
"set tags=$HOME/ctags/tags;/
set tags=./tags;,tags,$HOME/ctags/tags
set cpt-=t

"Open tag in the new tab
nnoremap <C-[><C-]> <C-w><C-]><C-w><S-t>

"Folding - works well with python
set foldmethod=manual
command! Fdi setlocal foldmethod=indent
"autocmd FileType python setlocal foldmethod=manual
"autocmd BufReadPre setlocal foldmethod=indent
set nofoldenable

function SaveSes(path)
    let s:saver = fnamemodify(getcwd(), ':t').'.vim'
    NERDTreeClose
    if empty(a:path)
        execute 'mks! '.s:saver
    elseif isdirectory(a:path)
        execute 'mks! 'a:path.'/'.s:saver
    else
        execute 'mks! Session.vim'
    endif
    echo getcwd()
endfunction
"Commands
:command -nargs=? Mkss :call  SaveSes(<q-args>)

"Svelte files as html
 au BufNewFile,BufReadPost *.svelte set syntax=html
"Verilog syntax highlitghting
 au BufNewFile,BufRead *.sv,*.svh,*.vh,*.v so ~/.vim/syntax/verilog_systemverilog.vim

 "Clipboard on wayland
 xnoremap <silent> *y :w !wl-copy<CR><CR>
 nnoremap <S-B> :ls t<CR>:b<Space>

 nnoremap <silent> ]b :bn<CR>
 nnoremap <silent> [b :bp<CR>

 nnoremap <silent> ]q :cnext<CR>
 nnoremap <silent> [q :cprevious<CR>

 "Fzf keybindings
 nnoremap <silent> <leader>ff :Files<CR>
 nnoremap <silent> <leader>fg :Rg<CR>
 nnoremap <silent> <leader>fb :Lines<CR>
 
" Pane navigation
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

function! PercentageResize()
    normal! <C-w>=
    let s:window_area = winwidth(0) * winheight(0)
    let s:screen_area = &columns * &lines
    let s:area_percentage = (s:window_area * 100.0) / s:screen_area

    if s:area_percentage > 65
        wincmd =
    else
        wincmd _
        wincmd |
    endif
endfunction

" Window maximize and minimize
nnoremap <C-W>m <C-W>\|<C-W>_
nnoremap <C-W>M <C-W>=
nnoremap <C-M> :call PercentageResize()<CR>

set statusline=%{winnr()}\ %f
